authors/urls.py
from django.urls import path

# from recipes.views import home
from . import views

# from recipes.views import contato, principal, sobre
# estamos importando as funções do arquivo views, da pasta recipes

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('register/create/', views.register_create, name="create"),
    path('login/', views.login_view, name="login"),
    path('login/create/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/recipe/new/', views.DashboardRecipe.as_view(),
         name="dashboard_recipe_new"),
    path('dashboard/recipe/delete/', views.DashboardRecipeDelete.as_view(),
         name="dashboard_recipe_delete"),
    path('dashboard/recipe/<int:id>/edit/', views.DashboardRecipe.as_view(),
         name="dashboard_recipe_edit"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# As urls das páginas do project estão no arquivo urls.py, na pasta recipes.
# Esse arquivo deverá ser importado através do include, para que as
# urls das páginas sejam reconhecidas.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

'''
Este código permite ao django mostrar na tela arquivos de
MEDIA_URL e STATIC_URL, quando solicitados
Precisa importar...
    from django.conf import settings
    from django.conf.urls.static import static
'''
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

# from recipes.views import home
from . import views

# from recipes.views import contato, principal, sobre
# estamos importando as funções do arquivo views, da pasta recipes

app_name = 'recipes'

urlpatterns = [
    path(
        '',
        views.RecipeListViewHome.as_view(),
        name="home"
    ),
    path(
        'recipes/search/',
        views.RecipeListViewSearch.as_view(),
        name="search"
    ),
    # <int:id> é o parâmetro (com o seu tipo int)
    # que será repassado para views.recipe
    # outros tipos: str (qualquer string),
    # slug (alfanumérico com - ou _) e uuid
    path(
        'recipes/category/<int:category_id>/',
        views.RecipeListViewCategory.as_view(),
        name="category"
    ),
    path(
        'recipes/<int:pk>/',
        views.RecipeDetail.as_view(),
        name="recipe"
    ),
    path(
        'recipes/api/v1/',
        views.RecipeListViewHomeApi.as_view(),
        name="recipe_api_v1"
    ),
    path(
        'recipes/api/v1/<int:pk>/',
        views.RecipeDetailApi.as_view(),
        name="recipe_api_v1_detail"
    ),
]

authors/forms/recipe_form.py
from collections import defaultdict

from attr import fields
from django import forms
from django.forms import ValidationError
from recipes.models import Recipe
from utils.django_forms import add_attr
from utils.strings import is_positive_number


class AuthorRecipeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_erros = defaultdict(list)

        add_attr(self.fields.get('preparation_steps'), 'class', 'span-2')

    class Meta:
        model = Recipe
        fields = 'title', 'description', 'preparation_time', \
            'preparation_time_unit', 'servings', 'servings_unit', \
            'preparation_steps', 'cover'
        widgets = {
            'cover': forms.FileInput(
                attrs={
                    'class': 'span-2'
                }
            ),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Pedaços', 'Pedaços'),
                    ('Pessoas', 'Pessoas'),
                )
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                )
            ),
        }

    # validação geral
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)

        cd = self.cleaned_data
        title = cd.get('title')
        description = cd.get('description')

        # verifica um erro de quantidade de caracteres em title
        # if len(title) < 5:
        #     self._my_erros['title'].append(
        #         'O título deve ter pelo menos 5 caracteres.'
        #     )

        # ----------------------------------------------------
        # verifica outros erros em title ou outros campos
        # ----------------------------------------------------
        if title == description:
            self._my_erros['title'].append(
                'Não pode ser igual a Descrição.'
            )
            self._my_erros['description'].append(
                'Não pode ser igual a Título.'
            )

        # levanta os erros encontrados
        if self._my_erros:
            raise ValidationError(self._my_erros)

        return super_clean

    def clean_title(self):
        title = self.cleaned_data.get('title')

        if len(title) < 5:
            self._my_erros['title'].append(
                'O título deve ter pelo menos 5 caracteres.'
            )

        return title

    def valid_field_number_positive(self, field_name):
        field_value = self.cleaned_data.get(field_name)
        if not is_positive_number(field_value) is True:
            self._my_erros[field_name].append('Deve ser um número positivo')

        return field_value

    def clean_preparation_time(self):
        return self.valid_field_number_positive('preparation_time')

    def clean_servings(self):
        return self.valid_field_number_positive('servings')

recipes/views.py
# from http.client import HTTPResponse
# from django.contrib.auth.decorators import login_required
from django.db.models import Q  # para usar OR (ou) no lugar de AND no filter
from django.forms.models import model_to_dict
from django.http import Http404, JsonResponse
# from django.shortcuts import render
# from django.shortcuts import get_object_or_404, render  # , get_list_or_404
from django.views.generic import DetailView, ListView
from utils.pagination import make_pagination

from recipes.models import Recipe

# from utils.recipes.factory import make_recipe

PER_PAGES = 9


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    ordering = ['-id']
    template_name = 'pages/home.html'

    # realiza a filtragem da lista de objetos
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True,
        )

        # para melhorar a performance da busca dos dados na base,
        # fazendo com que o django faça joins nas selects
        # onde houver ForenKey (um pra muitos)
        qs = qs.select_related('author', 'category')

        # se fosse o caso de muitos para muitos, seria a linha abaixo...
        # qs = qs.prefetch_related()

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('recipes'),
            PER_PAGES
        )
        ctx.update({
            'recipes': page_obj,
            'pagination_range': pagination_range,
        })
        return ctx


class RecipeListViewHome(RecipeListViewBase):
    template_name = 'pages/home.html'


class RecipeListViewHomeApi(RecipeListViewBase):
    template_name = 'pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data()['recipes']
        recipes_list = recipes.object_list.values()
        return JsonResponse(
            list(recipes_list),
            safe=False,
        )


class RecipeListViewCategory(RecipeListViewBase):
    template_name = 'pages/category.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)

        if (not qs):
            raise Http404()

        qs = qs.filter(
            category__id=self.kwargs.get('category_id'),
            is_published=True,
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({
            'title': f'{ctx.get("recipes")[0].category.name} - Category | '      # noqa: E501
        })

        return ctx


class RecipeListViewSearch(RecipeListViewBase):
    template_name = 'pages/search.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)

        search_term = self.request.GET.get('q', '').strip()

        if (not search_term) or (not qs):
            raise Http404()

        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term)
            ),
            is_published=True,
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        search_term = self.request.GET.get('q', '').strip()

        ctx.update({
            'page_title': f'Search for "{search_term}" | ',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}'
        })

        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)

        if (not qs):
            raise Http404()

        qs = qs.filter(
            is_published=True,
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)

        ctx.update({
            'is_detail_page': True,
        })

        return ctx


class RecipeDetailApi(RecipeDetail):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        # se existir o campo cover, atribui apenas a url
        if recipe_dict.get('cover'):
            recipe_dict['cover'] = self.request.build_absolute_uri() + \
                recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''

        # deleta o campo is_published do dicionário recipe_dict
        # para que o mesmo não seja exibido nos atributos
        del recipe_dict['is_published']
        del recipe_dict['preparation_steps_is_html']

        # na falta de um campo, podemos adicioná-lo manualmente
        # como é o caso de created_at
        recipe_dict['created_at'] = str(recipe.created_at)
        recipe_dict['updated_at'] = str(recipe.updated_at)

        return JsonResponse(
            recipe_dict,
            safe=False,
        )


'''
def home(request):
    # recipes = Recipe.objects.all().order_by('-id')
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    # para enviar mensagens ao template...
    # from django.contrib import messages
    # exemplo de mensagens, cujas tags css estão
    # embutidas no settings.py
    # messages.success(request, 'Sua pesquisa foi efetuada.')
    # messages.error(request, 'Esta é uma mensagem de erro.')
    # messages.error(request, 'Esta é outra mensagem de erro.')
    # messages.info(request, 'Esta é uma mensagem informativa.')

    return render(request, 'pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
    })
    # return render(request, 'pages/home.html', context={
    # 'recipes': [make_recipe() for _ in range(10)],
    # })


def search(request):
    # request.GET.get('q') retorna o mesmo que request.GET['q']
    # porém, quando vazio, o primeiro retorna None
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404('Página não encontrada. 🤪')

    # faz a busca de receitas com base no que foi digitado
    # o Q() permite personalizar o operador lógico: & (and), | (or)
    recipes = Recipe.objects.filter(
        # __icontains faz a funções de um like (contém)
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        ),
        is_published=True,
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    return render(request, 'pages/search.html', {
        'page_title': f'Search for "{search_term}" | ',
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}'
    })


def category(request, category_id):
    recipes = Recipe.objects.filter(
        category__id=category_id, is_published=True).order_by('-id')

    if not recipes:
        raise Http404('Página não encontrada. 🤪')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGES)

    return render(request, 'pages/category.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': f'Category {recipes.first().category.name} - Category | '
    })


def recipe(request, id):
    # recipe = Recipe.objects.filter(
    #     pk=id, is_published=True).order_by('-id').first()

    # if not recipe:
    #     raise Http404('Página não encontrada. :(')

    recipe = get_object_or_404(
        Recipe,
        pk=id,
        is_published=True
    )

    return render(request, 'pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })
'''

recipes/templates/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Dimes Dias</a>
  </div>

  <div class="powered">
    <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>
</footer> 

recipes/templates/partials/head.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- links externos incluídos: para uso de ícones -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- link para o Google Font "Roboto Slab" -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <!-- link do arquivo static css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- título da página -->
    <title>Project in DJANGO</title>

</head>

recipes/templates/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">
                    Recipes
                </span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/partials/messages.html
{% if messages %}
    <div class="main-content centraliza container messages-container">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

recipes/templates/partials/pagination.html
{% if recipes.has_other_pages %}
    <div class="container pagination">
        <div class="pagination-content">

            {% if pagination_range.first_page_out_of_range %}
                <a href="?page=1{{ additional_url_query }}" class="page-link page-item">1</a>
                <span class="page-item">...</span>
            {% endif %}

            {% for page in pagination_range.pagination %}
                {% if pagination_range.current_page == page %}
                    <span class="page-link page-item page-current">{{ page }}</span>
                {% else %}
                    <a href="?page={{ page }}{{ additional_url_query }}" class="page-link page-item">{{ page }}</a>
                {% endif %}
            {% endfor %}

            {% if pagination_range.last_page_out_of_range %}
                <span class="page-item">...</span>
                <a href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}" class="page-link page-item">{{ pagination_range.total_pages }}</a>
            {% endif %}

        </div>
    </div>
{% endif %}
        

recipes/templates/partials/recipe.html
<div class="recipe recipe-list-item">
    {% comment %} verifica se cover possui uma imagem associada {% endcomment %}
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <!-- <img src="https://via.placeholder.com/1280x720.png/269fe6" alt="Temporário"> -->
            <!-- <img src="https://source.unsplash.com/random/1280x720" alt="Temporário"> -->
            {% if recipe.cover %}
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            {% else %}
                <img src="/media/recipes/covers/imagem_padrao.jpg" alt="Temporário">
            {% endif %}
        </a>
    </div>

    <!-- recipe é a variável passada pelo for de home.html -->
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe.title }}</a>
        </h2>
    </div>

    <div class="recipe-author">
        {% if not recipe.author is None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            </span>
        {% endif %}
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:'d-m-Y à\s H:i:s' }}
        </span>

        {% if not recipe.category is None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% comment %} qualquer uma das formas funcionaria
    {% if is_detail_page is not True %}
    {% if not is_detail_page %}
    {% if is_detail_page != True %} {% endcomment %}

    {% if not is_detail_page is True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {% comment %} se houver código HTML embutido, formata a exibição {% endcomment %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {% comment %} faz a exibição normal do texto puro {% endcomment %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}

</div>

recipes/templates/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{ search_term }}" required placeholder="Pesquisar uma receita">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>